### ISSUE TITLE
Conflict with latest version of Docker Desktop

### ISSUE THREAD

**Issue by GriffinJohnston** [pantheon-systems/localdev-issues#57]
After upgrading to the latest version of Docker Desktop for MacOS (v 2.3.0.2) - LocalDev is giving me a "Docker Sync Required" error. I've tried a couple things to no avail:

1. Allowing LD to "Sync Docker" - this creates a conflict with Docker Desktop
2. Switching to "edge" release

Is LocalDev just not intended to be compatible with DD?

Thank you!

**Comment by pirog** [comment]
@GriffinJohnston Localdev uses Docker Desktop behind the scenes. 

However, sometimes the user will upgrade Docker Desktop to a version that is currently ahead of what we've tested for use with Localdev so the purpose of the warning is to communicate to the user that they are using a version of Docker Desktop that is not not supported for use with Localdev. I think that:

1. The warning needs to be explained better, because its not clear
2. There should probably be a "Danger button" where the user can say "cool, i understand, but i dont care, let me use what i have and i accept the consequences eg that i am doing something usupported"

**Comment by GriffinJohnston** [comment]
@pirog Thanks for the explanation! Your second idea is definitely needed — I use docker for a lot outside of Drupal/WP/Pantheon, so keeping it out of date to make localDev happy doesn't feel great. I'd love an option to go ahead and run LocalDev anyway, with the understanding that it may not be stable.

**Comment by pirog** [comment]
@GriffinJohnston yup, we figured this would be requested sooner rather than later but wanted to get more feedback which is why this is currently only on the `edge` channel. 

It's a tough problem but i think defaulting to what we need to ensure some level stability for Localdev with an opt-out is probably the best we can do.

**Comment by GriffinJohnston** [comment]
Makes sense - thanks for the quick reply.

**Comment by pirog** [comment]
@GriffinJohnston going to keep this open so we have something to track this!

**Comment by GriffinJohnston** [comment]
@pirog Looks like the option was added in a recent update?

<img width="1080" alt="Screen Shot 2020-07-06 at 1 53 30 PM" src="https://user-images.githubusercontent.com/6344312/86623775-1f53c180-bf90-11ea-93d6-3ee7943446b1.png">
